name: libnpa apk builder
run-name: Build apk ${{ github.ref_name }}

on:
  push:
    branches:
      - '*'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jirutka/setup-alpine@v1
      with:
        branch: latest-stable
        packages: >
          boost-dev
          make
          cmake
          clang
          flex-dev
          git
          bison
          alpine-sdk
          bash
          apk-tools

    - name: Setup build environment
      run: |
        adduser -D abuilder
        addgroup abuilder abuild
        addgroup abuilder wheel
        
        echo "permit nopass :wheel" > /etc/doas.conf
        chown root:root /etc/doas.conf
        chmod 0400 /etc/doas.conf
        
        mkdir -p /var/cache/distfiles
        chown root:abuild /var/cache/distfiles
        chmod 775 /var/cache/distfiles
        
        mkdir -p /home/abuilder/.abuild
        echo "PACKAGER=\"GitHub Actions <actions@github.com>\"" > /home/abuilder/.abuild/abuild.conf
        su - abuilder -c "abuild-keygen -n -a -i"
      shell: alpine.sh --root {0}

    - name: Build APK
      run: |
        mkdir -p libnpa
        cd libnpa

        cat > APKBUILD << 'EOF'
        # Maintainer:
        pkgname=libnpa
        pkgver=0.5.3
        pkgrel=0
        pkgdesc="library for manipulating Nitroplus game files"
        url="https://github.com/Madagambada/libnpa"
        arch="all"
        license="MIT"
        options="!check"
        depends="boost-libs zlib"
        makedepends="cmake samurai boost-dev zlib-dev flex bison"
        subpackages="$pkgname-dev"
        source="https://github.com/Madagambada/libnpa/archive/refs/tags/libnpa-$pkgver.tar.gz"
        builddir="$srcdir/libnpa-libnpa-$pkgver"

        build() {
            cd "$builddir"
            
            local crossopts=""
            [ "$CBUILD" != "$CHOST" ] && crossopts="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"

            cmake -B build -G Ninja \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DCMAKE_BUILD_TYPE=Release \
                -DBoost_USE_STATIC_LIBS=OFF \
                $crossopts .
            
            cmake --build build
        }

        package() {
            cd "$builddir/build"
            DESTDIR="$pkgdir" cmake --install .
        }
        EOF
        
        export CBUILD="$(uname -m)-alpine-linux-musl"
        export CARCH="$(uname -m)"
        su - abuilder -c "cd '$PWD' && abuild checksum"
        su - abuilder -c "cd '$PWD' && abuild -r"
      shell: alpine.sh --root {0}

    - name: Release APK
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        generate_release_notes: true
        files: /home/abuilder/packages/**/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
