name: libnpa Release builder
run-name: Release Build ${{ github.ref_name }}

on:
  push:
    tags:
        - "libnpa-v*.*.*"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        packages: >
          boost-dev
          make
          cmake
          clang
          flex-dev
          git
          bison
          doas

    - name: build
      run: |
        echo "::group::Configure"
        mkdir build
        cd build
        export CXX=clang++
        export CC=clang
        cmake -DCMAKE_BUILD_TYPE=Release ..
        echo "::endgroup::"
        echo "::group::Build"
        make -j4
        echo "::endgroup::"
        cpack
      shell: alpine.sh {0}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /home/runner/work/libnpa/libnpa/build/libnpa-${{ github.ref_name }}-Linux.tar.bz2
        asset_name: libnpa-${{ github.event.release.tag_name }}.tar.bz2
        asset_content_type: application/x-bzip2
